import type { SupabaseClient } from "@supabase/supabase-js";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { PlanetPosition } from "../ephemeris/adapter";
import {
  computePromptAspects,
  generateAndPersistHoroscope,
  isHoroscopeEnabled,
  type StoredReadingForGeneration,
} from "./generate";
import * as horoscope from "./horoscope";

// Sun + Moon only -- composeChart's moon phase step requires both to be
// present; the other tests in this file don't care about full accuracy,
// only that buildReadingModel can run without throwing.
const MINIMAL_POSITIONS: PlanetPosition[] = [
  { body: "Sun", eclipticLongitude: 10, sign: "Aries", degreeInSign: 10, retrograde: false },
  { body: "Moon", eclipticLongitude: 40, sign: "Taurus", degreeInSign: 10, retrograde: false },
];

const READING: StoredReadingForGeneration = {
  id: "11111111-1111-1111-1111-111111111111",
  event_date: "1977-03-31",
  positions: MINIMAL_POSITIONS,
  events: null,
  horoscope: null,
};

function fakeAnon(rpcResult: { data: unknown; error: unknown }) {
  return { rpc: vi.fn().mockResolvedValue(rpcResult) } as unknown as SupabaseClient;
}

afterEach(() => {
  vi.unstubAllEnvs();
  vi.restoreAllMocks();
});

describe("isHoroscopeEnabled (R6)", () => {
  it("is enabled when the flag is absent", () => {
    expect(isHoroscopeEnabled({})).toBe(true);
  });

  it("is enabled for any value other than an explicit disable", () => {
    expect(isHoroscopeEnabled({ HOROSCOPE_ENABLED: "true" })).toBe(true);
    expect(isHoroscopeEnabled({ HOROSCOPE_ENABLED: "on" })).toBe(true);
    expect(isHoroscopeEnabled({ HOROSCOPE_ENABLED: "flase" })).toBe(true); // a typo is still enabled
  });

  it("is disabled only for an explicit false, case-insensitively", () => {
    expect(isHoroscopeEnabled({ HOROSCOPE_ENABLED: "false" })).toBe(false);
    expect(isHoroscopeEnabled({ HOROSCOPE_ENABLED: "FALSE" })).toBe(false);
    expect(isHoroscopeEnabled({ HOROSCOPE_ENABLED: " false " })).toBe(false);
  });
});

/**
 * Sprint 14 fixture (1977-03-31), same positions as lib/chart/model.test.ts.
 * Unlike composeChart's own test, this asserts the Application column too
 * -- docs/design/CHART_MODEL.md's original table, generated by this exact
 * method (a real one-day-later snapshot) before Sprint 15's composeChart
 * made `applying` structurally false. This is the regression test QA1's
 * Sprint 17 round-1 finding asked for: a shape this function can actually
 * produce, checked against real recorded values, not an asserted-but-
 * impossible fixture.
 */
const FIXTURE_POSITIONS: PlanetPosition[] = [
  { body: "Sun", eclipticLongitude: 10.657, sign: "Aries", degreeInSign: 10.66, retrograde: false },
  { body: "Moon", eclipticLongitude: 142.451, sign: "Leo", degreeInSign: 22.45, retrograde: false },
  { body: "Mercury", eclipticLongitude: 25.5231, sign: "Aries", degreeInSign: 25.52, retrograde: false },
  { body: "Venus", eclipticLongitude: 19.8669, sign: "Aries", degreeInSign: 19.87, retrograde: true },
  { body: "Mars", eclipticLongitude: 338.8993, sign: "Pisces", degreeInSign: 8.9, retrograde: false },
  { body: "Jupiter", eclipticLongitude: 59.3903, sign: "Taurus", degreeInSign: 29.39, retrograde: false },
  { body: "Saturn", eclipticLongitude: 130.0549, sign: "Leo", degreeInSign: 10.05, retrograde: true },
  { body: "Uranus", eclipticLongitude: 220.9488, sign: "Scorpio", degreeInSign: 10.95, retrograde: true },
  { body: "Neptune", eclipticLongitude: 256.0949, sign: "Sagittarius", degreeInSign: 16.09, retrograde: true },
  { body: "Pluto", eclipticLongitude: 192.8839, sign: "Libra", degreeInSign: 12.88, retrograde: true },
];

const EXPECTED_ASPECTS: {
  bodyA: string;
  bodyB: string;
  aspect: string;
  orb: number;
  tightness: number;
  applying: boolean;
}[] = [
  { bodyA: "Sun", bodyB: "Saturn", aspect: "trine", orb: 0.6, tightness: 0.914, applying: false },
  { bodyA: "Saturn", bodyB: "Uranus", aspect: "square", orb: 0.89, tightness: 0.872, applying: true },
  { bodyA: "Mars", bodyB: "Uranus", aspect: "trine", orb: 2.05, tightness: 0.707, applying: true },
  { bodyA: "Sun", bodyB: "Pluto", aspect: "opposition", orb: 2.23, tightness: 0.722, applying: true },
  { bodyA: "Moon", bodyB: "Venus", aspect: "trine", orb: 2.58, tightness: 0.631, applying: false },
  { bodyA: "Saturn", bodyB: "Pluto", aspect: "sextile", orb: 2.83, tightness: 0.293, applying: true },
  { bodyA: "Moon", bodyB: "Mercury", aspect: "trine", orb: 3.07, tightness: 0.561, applying: false },
  { bodyA: "Neptune", bodyB: "Pluto", aspect: "sextile", orb: 3.21, tightness: 0.197, applying: false },
  { bodyA: "Venus", bodyB: "Neptune", aspect: "trine", orb: 3.77, tightness: 0.461, applying: true },
  { bodyA: "Sun", bodyB: "Neptune", aspect: "trine", orb: 5.44, tightness: 0.223, applying: true },
  { bodyA: "Mercury", bodyB: "Venus", aspect: "conjunction", orb: 5.66, tightness: 0.293, applying: false },
  { bodyA: "Saturn", bodyB: "Neptune", aspect: "trine", orb: 6.04, tightness: 0.137, applying: false },
  { bodyA: "Moon", bodyB: "Neptune", aspect: "trine", orb: 6.36, tightness: 0.092, applying: false },
  { bodyA: "Moon", bodyB: "Jupiter", aspect: "square", orb: 6.94, tightness: 0.009, applying: true },
  { bodyA: "Venus", bodyB: "Pluto", aspect: "opposition", orb: 6.98, tightness: 0.127, applying: true },
];

describe("computePromptAspects", () => {
  it("reproduces CHART_MODEL.md's original Application column, including applying (QA1 Sprint 17 round 1)", () => {
    const aspects = computePromptAspects("1977-03-31", FIXTURE_POSITIONS);
    expect(aspects).toHaveLength(EXPECTED_ASPECTS.length);
    EXPECTED_ASPECTS.forEach((expected, i) => {
      expect(aspects[i].bodyA).toBe(expected.bodyA);
      expect(aspects[i].bodyB).toBe(expected.bodyB);
      expect(aspects[i].aspect).toBe(expected.aspect);
      expect(aspects[i].orb).toBeCloseTo(expected.orb, 2);
      expect(aspects[i].tightness).toBeCloseTo(expected.tightness, 2);
      expect(aspects[i].applying).toBe(expected.applying);
    });
  });
});

describe("generateAndPersistHoroscope", () => {
  it("does not call OpenAI or write when disabled (R6, R7)", async () => {
    vi.stubEnv("HOROSCOPE_ENABLED", "false");
    const generateSpy = vi.spyOn(horoscope, "generateHoroscope");
    const anon = fakeAnon({ data: null, error: null });

    const result = await generateAndPersistHoroscope(anon, "some-id", READING);

    expect(result).toEqual({ ok: false, error: "Horoscope generation is currently disabled." });
    expect(generateSpy).not.toHaveBeenCalled();
    expect(anon.rpc).not.toHaveBeenCalled();
  });

  it("builds the prompt from prompt-accurate aspects, not composeChart's own always-false ones", async () => {
    const generateSpy = vi
      .spyOn(horoscope, "generateHoroscope")
      .mockResolvedValue({ text: "text", model: "gpt-4o-mini" });
    const anon = fakeAnon({ data: true, error: null });

    await generateAndPersistHoroscope(anon, "some-id", { ...READING, positions: FIXTURE_POSITIONS });

    const readingModelArg = generateSpy.mock.calls[0][0];
    expect(readingModelArg.chart.aspects.some((a) => a.applying)).toBe(true);
  });

  it("surfaces a generation failure and performs no write (R8)", async () => {
    vi.spyOn(horoscope, "generateHoroscope").mockRejectedValue(new Error("OpenAI request failed: 429"));
    const anon = fakeAnon({ data: null, error: null });

    const result = await generateAndPersistHoroscope(anon, "some-id", READING);

    expect(result).toEqual({ ok: false, error: "Horoscope generation failed, try again." });
    expect(anon.rpc).not.toHaveBeenCalled();
  });

  it("surfaces a persistence failure without claiming success (R8)", async () => {
    vi.spyOn(horoscope, "generateHoroscope").mockResolvedValue({ text: "text", model: "gpt-4o-mini" });
    const anon = fakeAnon({ data: null, error: { message: "db error" } });

    const result = await generateAndPersistHoroscope(anon, "some-id", READING);

    expect(result).toEqual({ ok: false, error: "Could not save the horoscope, try again." });
  });

  it("persists exactly the generated text and model via set_reading_horoscope on success", async () => {
    vi.spyOn(horoscope, "generateHoroscope").mockResolvedValue({
      text: "A horoscope about Fire signs.",
      model: "gpt-4o-mini-2024-07-18",
    });
    const anon = fakeAnon({ data: true, error: null });

    const result = await generateAndPersistHoroscope(anon, "reading-id-123", READING);

    expect(result).toEqual({ ok: true });
    expect(anon.rpc).toHaveBeenCalledWith("set_reading_horoscope", {
      reading_id: "reading-id-123",
      horoscope: "A horoscope about Fire signs.",
      model: "gpt-4o-mini-2024-07-18",
    });
  });
});
