import { describe, expect, it } from "vitest";
import type { PlanetPosition } from "../ephemeris/adapter";
import { composeChart } from "./model";

/**
 * Sprint 14 fixture (1977-03-31), values from docs/design/CHART_MODEL.md's
 * worked example -- generated by running the Sprint 12 engine directly, not
 * by calling composeChart, so this test proves composeChart reproduces them
 * from stored positions rather than assuming it does.
 */
const FIXTURE_POSITIONS: PlanetPosition[] = [
  { body: "Sun", eclipticLongitude: 10.657, sign: "Aries", degreeInSign: 10.66, retrograde: false },
  { body: "Moon", eclipticLongitude: 142.451, sign: "Leo", degreeInSign: 22.45, retrograde: false },
  { body: "Mercury", eclipticLongitude: 25.5231, sign: "Aries", degreeInSign: 25.52, retrograde: false },
  { body: "Venus", eclipticLongitude: 19.8669, sign: "Aries", degreeInSign: 19.87, retrograde: true },
  { body: "Mars", eclipticLongitude: 338.8993, sign: "Pisces", degreeInSign: 8.9, retrograde: false },
  { body: "Jupiter", eclipticLongitude: 59.3903, sign: "Taurus", degreeInSign: 29.39, retrograde: false },
  { body: "Saturn", eclipticLongitude: 130.0549, sign: "Leo", degreeInSign: 10.05, retrograde: true },
  { body: "Uranus", eclipticLongitude: 220.9488, sign: "Scorpio", degreeInSign: 10.95, retrograde: true },
  { body: "Neptune", eclipticLongitude: 256.0949, sign: "Sagittarius", degreeInSign: 16.09, retrograde: true },
  { body: "Pluto", eclipticLongitude: 192.8839, sign: "Libra", degreeInSign: 12.88, retrograde: true },
];

// bodyA/bodyB/aspect/orb/tightness from CHART_MODEL.md's 15-row table,
// sorted tightest first. `applying` is deliberately not drawn from that
// table's Application column -- see model.ts's comment on why composeChart
// can't reproduce it (no second position snapshot without computePositions,
// which R4 forbids), and is asserted separately below as always false.
const EXPECTED_ASPECTS: { bodyA: string; bodyB: string; aspect: string; orb: number; tightness: number }[] = [
  { bodyA: "Sun", bodyB: "Saturn", aspect: "trine", orb: 0.6, tightness: 0.914 },
  { bodyA: "Saturn", bodyB: "Uranus", aspect: "square", orb: 0.89, tightness: 0.872 },
  { bodyA: "Mars", bodyB: "Uranus", aspect: "trine", orb: 2.05, tightness: 0.707 },
  { bodyA: "Sun", bodyB: "Pluto", aspect: "opposition", orb: 2.23, tightness: 0.722 },
  { bodyA: "Moon", bodyB: "Venus", aspect: "trine", orb: 2.58, tightness: 0.631 },
  { bodyA: "Saturn", bodyB: "Pluto", aspect: "sextile", orb: 2.83, tightness: 0.293 },
  { bodyA: "Moon", bodyB: "Mercury", aspect: "trine", orb: 3.07, tightness: 0.561 },
  { bodyA: "Neptune", bodyB: "Pluto", aspect: "sextile", orb: 3.21, tightness: 0.197 },
  { bodyA: "Venus", bodyB: "Neptune", aspect: "trine", orb: 3.77, tightness: 0.461 },
  { bodyA: "Sun", bodyB: "Neptune", aspect: "trine", orb: 5.44, tightness: 0.223 },
  { bodyA: "Mercury", bodyB: "Venus", aspect: "conjunction", orb: 5.66, tightness: 0.293 },
  { bodyA: "Saturn", bodyB: "Neptune", aspect: "trine", orb: 6.04, tightness: 0.137 },
  { bodyA: "Moon", bodyB: "Neptune", aspect: "trine", orb: 6.36, tightness: 0.092 },
  { bodyA: "Moon", bodyB: "Jupiter", aspect: "square", orb: 6.94, tightness: 0.009 },
  { bodyA: "Venus", bodyB: "Pluto", aspect: "opposition", orb: 6.98, tightness: 0.127 },
];

describe("composeChart", () => {
  it("reproduces the Sprint 14 fixture's date, Julian Day, and stored positions", () => {
    const chart = composeChart("1977-03-31", FIXTURE_POSITIONS);
    expect(chart.date).toBe("1977-03-31");
    expect(chart.julianDay).toBe(2443234);
    // Same reference, not a recomputed/cloned copy -- R4.
    expect(chart.positions).toBe(FIXTURE_POSITIONS);
  });

  it("reproduces every aspect from the fixture, sorted tightest first", () => {
    const { aspects } = composeChart("1977-03-31", FIXTURE_POSITIONS);
    expect(aspects).toHaveLength(EXPECTED_ASPECTS.length);
    EXPECTED_ASPECTS.forEach((expected, i) => {
      expect(aspects[i].bodyA).toBe(expected.bodyA);
      expect(aspects[i].bodyB).toBe(expected.bodyB);
      expect(aspects[i].aspect).toBe(expected.aspect);
      expect(aspects[i].orb).toBeCloseTo(expected.orb, 2);
      expect(aspects[i].tightness).toBeCloseTo(expected.tightness, 2);
    });
  });

  it("applying is always false -- no second position snapshot to determine it from", () => {
    const { aspects } = composeChart("1977-03-31", FIXTURE_POSITIONS);
    expect(aspects.every((a) => a.applying === false)).toBe(true);
  });

  it("reproduces the fixture's element and modality balance", () => {
    const chart = composeChart("1977-03-31", FIXTURE_POSITIONS);
    expect(chart.elements).toEqual({ Fire: 6, Earth: 1, Air: 1, Water: 2 });
    expect(chart.modalities).toEqual({ Cardinal: 4, Fixed: 4, Mutable: 2 });
  });

  it("reproduces the fixture's moon phase", () => {
    const { moonPhase } = composeChart("1977-03-31", FIXTURE_POSITIONS);
    expect(moonPhase.phaseName).toBe("Waxing gibbous");
    expect(moonPhase.waxing).toBe(true);
    expect(moonPhase.elongation).toBeCloseTo(131.79, 2);
  });

  it("rejects a date before 1700-01-01", () => {
    expect(() => composeChart("1699-12-31", FIXTURE_POSITIONS)).toThrow(/1700-01-01/);
  });

  it("rejects a date after 2100-12-31", () => {
    expect(() => composeChart("2101-01-01", FIXTURE_POSITIONS)).toThrow(/2100-12-31/);
  });
});
